name: CodeQuality-Valgrind
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
  
    - name: make test
      run: make -C 3_Implementation/ test/test_ARLS.c
    - name: Valgrid
      run: 
          echo Add other actions to build,
          echo test, and deploy your project.
